networks:
  app_network:
    driver: bridge

services:
  app:
    networks:
      - app_network
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  celery:
    build: .
    env_file: .env
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: celery -A app.tasks.celery_app worker -l info

  postgres:
    networks:
      - app_network
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: support_triager
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d support_triager"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    networks:
      - app_network
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
